#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from turtlesim.srv import TeleportAbsolute

class TurtleTeleporter(Node):
    def __init__(self):
        super().__init__('turtle_teleporter')
        self.client = self.create_client(TeleportAbsolute, '/turtle1/teleport_absolute')
        while not self.client.wait_for_service(timeout_sec=1.0):
            self.get_logger().info('Waiting for teleport service...')

        self.req = TeleportAbsolute.Request()
        self.req.x = 5.0
        self.req.y = 5.0
        self.req.theta = 1.57
        self.call_service()

    def call_service(self):
        future = self.client.call_async(self.req)
        future.add_done_callback(self.callback)

    def callback(self, future):
        self.get_logger().info('Teleportation Done!')

def main(args=None):
    rclpy.init(args=args)
    node = TurtleTeleporter()
    rclpy.spin(node)
    rclpy.shutdown()

