#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from custom_message.msg import Person

class PersonPublisher(Node):
    def __init__(self):
        super().__init__('person_publisher')
        self.publisher_ = self.create_publisher(Person, 'person_topic', 10)
        self.timer = self.create_timer(1.0, self.publish_person)
        self.get_logger().info("Person publisher has been started.")

    def publish_person(self):
        msg = Person()
        msg.name = 'Alice'
        msg.age = 25
        self.publisher_.publish(msg)
        self.get_logger().info(f'Published: {msg.name}, {msg.age}')

def main(args=None):
    rclpy.init(args=args)
    node = PersonPublisher()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
